// ... [your entire code above remains unchanged] ...

/* ---------- JPEG Export ---------- */
// Replace the old JPEG export code with DeepAI Genius integration

// Helper: build prompt from selections
function buildDeepAIPrompt() {
  // Get friendly labels
  const bodyLabel = bodyOptions[selected.body].label || '';
  
  // Hair color from thumb filename or add .label to hairOptions for clarity
  let hairLabel = '';
  if (hairOptions[selected.hair].thumb.includes('blck')) hairLabel = "black";
  else if (hairOptions[selected.hair].thumb.includes('red')) hairLabel = "red";
  else if (hairOptions[selected.hair].thumb.includes('blnd') || hairOptions[selected.hair].thumb.includes('bond')) hairLabel = "blonde";
  else hairLabel = "fantasy";
  
  // Eye color
  let eyeLabel = '';
  if (eyesOptions[selected.eyes].thumb.includes('blu')) eyeLabel = "blue";
  else if (eyesOptions[selected.eyes].thumb.includes('brn')) eyeLabel = "brown";
  else if (eyesOptions[selected.eyes].thumb.includes('green')) eyeLabel = "green";
  else if (eyesOptions[selected.eyes].thumb.includes('redbrn')) eyeLabel = "red-brown";
  else eyeLabel = "fantasy";

  // Face type
  let faceLabel = '';
  if (faceOptions[selected.face].thumb.includes('full')) faceLabel = "full face";
  else if (faceOptions[selected.face].thumb.includes('norm')) faceLabel = "normal face";
  else faceLabel = "fantasy face";

  // Armaments (gear)
  let gearLabel = '';
  // If you want to use armamentsOptions, you need to track selected.armaments
  // For now, use the label of the first armaments option or generic
  gearLabel = armamentsOptions[0].label || "fantasy armor";

  // Compose prompt
  return `A fantasy RPG character with a ${bodyLabel.toLowerCase()} build, ${hairLabel} hair, ${eyeLabel} eyes, ${faceLabel}, ${gearLabel}, high quality game art, white background`;
}

document.getElementById("showJpegBtn").addEventListener("click", async () => {
  const prompt = buildDeepAIPrompt();

  // Show loading state
  const jpg = document.getElementById("jpegPreview");
  jpg.style.display = "none";
  document.getElementById("saveInstr").style.display = "block";
  document.getElementById("saveInstr").innerHTML = "Generating AI image, please wait...";

  try {
    const resp = await fetch("https://api.deepai.org/api/genius", {
      method: "POST",
      headers: {
        "Api-Key": "a516b9aa-e8ba-4342-bd6a-59b82768b002",
        "Content-Type": "application/x-www-form-urlencoded"
      },
      body: `text=${encodeURIComponent(prompt)}`
    });

    const data = await resp.json();
    if (data && data.output_url) {
      jpg.src = data.output_url;
      jpg.style.display = "block";
      document.getElementById("saveInstr").style.display = "block";
      document.getElementById("saveInstr").innerHTML =
        'Long-press or right-click the image above to save your character as a JPEG.<br><span style="color:#c55;font-size:1.3em;">AI generated by DeepAI Genius</span>';
      document.getElementById("charCanvas").style.display = "none";
      document.getElementById("editingButtons").style.display = "none";
      document.getElementById("jpegButtons").style.display = "block";
    } else {
      jpg.style.display = "none";
      document.getElementById("saveInstr").style.display = "block";
      document.getElementById("saveInstr").innerHTML = "Image generation failed. Please try again.";
    }
  } catch (err) {
    jpg.style.display = "none";
    document.getElementById("saveInstr").style.display = "block";
    document.getElementById("saveInstr").innerHTML = "Image generation failed. Please try again.";
  }
});

document.getElementById("backBtn").addEventListener("click",()=>{
  document.getElementById("jpegPreview").style.display = "none";
  document.getElementById("saveInstr").style.display   = "none";
  document.getElementById("charCanvas").style.display  = "block";
  document.getElementById("editingButtons").style.display = "block";
  document.getElementById("jpegButtons").style.display = "none";
});
