name = "sorc-app"
main = "src/index.ts"
compatibility_date = "2025-05-06"
workers_dev = true
account_id = "d771bbe6613a9064911ecc7e6b3fe10b"

[[d1_databases]]
binding = "sorc_db"
database_name = "sorc-rpg"
database_id = "256008d3-fd04-4766-8883-0796624b9cb5"

[[kv_namespaces]]
binding = "SESSIONS"
id = "9a9c20a6e14a4a42b635e8a6fb861bfb"

[[r2_buckets]]
binding = "AVATARS"
bucket_name = "sorc-avatars"

[[r2_buckets]]
binding = "FORUM_MEDIA"
bucket_name = "sorc-forum-media"

[env.production]
vars = { ENVIRONMENT = "production", API_URL = "https://api.sorcrpg.com" }

[env.development]
vars = { ENVIRONMENT = "development", API_URL = "http://localhost:8787" }

[triggers]
crons = ["0 0 * * *"]
